export const constants = {
  home: 'Home',
  content: 'Content',
  common: 'Common',
  report: 'Report',
  admin: 'Admin',
  companies: 'Companies',
  company: 'Company',
  contactUs: 'ContactUs',
  aboutUs: 'AboutUs',
  login: 'Login',
  register: 'Register',
  registerCompany: 'RegisterCompany',
  forgotPassword: 'ForgotPassword',
  changePassword: 'ChangePassword',
  welcome: 'Welcome',
  advancedSearch: 'AdvancedSearch',
  jobPositions: 'JobPositions',
  jobPosition: 'JobPosition',
  jobPositionDetail: 'JobPositionDetail',
  descriptors: 'Descriptors',
  descriptor: 'Descriptor',
  descriptorProcess: 'DescriptorProcess',
  socioEconomicInterviews: 'SocioeconomyInterviews',
  appointments: 'Appointments',
  services: 'Services',
  service: 'Service',
  approveJobPositions: 'ApproveJobPositions',
  approveDocuments: 'ApproveDocuments',
  approvePayments: 'ApprovePayments',
  changeProfilePicture: 'ChangeProfilePicture',
  candidate: 'Candidate',
  profile: 'Profile',
  interview: 'Interview',
  updateInterviewVideo: 'UpdateInterviewVideo',
  addCompany: 'AddCompany',
  addJobOffer: 'AddJobOffer',
  addDescriptor: 'AddDescriptor',
  addService: 'AddService',
  error: 'Error',
};

export const routes = {
  home: {
    index: `/${constants.home}`,
    companies: `/${constants.home}/${constants.companies}`,
    contactUs: `/${constants.home}/${constants.contactUs}`,
    aboutUs: `/${constants.home}/${constants.aboutUs}`,
    login: `/${constants.home}/${constants.login}`,
    register: `/${constants.home}/${constants.register}`,
    registerCompany: `/${constants.home}/${constants.registerCompany}`,
    forgotPassword: `/${constants.home}/${constants.forgotPassword}`,
  },
  welcome: `/${constants.welcome}`,
  company: {
    services: `/${constants.company}/${constants.services}`,
    service: `/${constants.company}/${constants.service}`,
    socioEconomicInterviews: `/${constants.company}/${constants.socioEconomicInterviews}`,
  },
  content: {
    index: `/${constants.content}`,
    advancedSearch: `/${constants.content}/${constants.advancedSearch}`,
    companies: `/${constants.content}/${constants.companies}`,
    services: `/${constants.content}/${constants.services}`,
    service: `/${constants.content}/${constants.service}`,
    company: `/${constants.content}/${constants.company}`,
    jobPositions: `/${constants.content}/${constants.jobPositions}`,
    jobPosition: `/${constants.content}/${constants.jobPosition}`,
    jobPositionDetail: `/${constants.content}/${constants.jobPositionDetail}`,
    descriptors: `/${constants.content}/${constants.descriptors}`,
    jobDescriptor: `/${constants.content}/${constants.descriptor}`,
    descriptorProcess: `/${constants.content}/${constants.descriptorProcess}`,
    appointments: `/${constants.content}/${constants.appointments}`,
    interview: `/${constants.content}/${constants.interview}`,
    updateInterviewVideo: `/${constants.content}/${constants.updateInterviewVideo}`,
    approveJobPositions: `/${constants.content}/${constants.approveJobPositions}`,
    approveDocuments: `/${constants.content}/${constants.approveDocuments}`,
    approvePayments: `/${constants.content}/${constants.approvePayments}`,
    changeProfilePicture: `/${constants.content}/${constants.changeProfilePicture}`,
    socioEconomicInterviews: `/${constants.content}/${constants.socioEconomicInterviews}`,
    addCompany: `/${constants.content}/${constants.addCompany}`,
    addJobOffer: `/${constants.content}/${constants.addJobOffer}`,
    addDescriptor: `/${constants.content}/${constants.addDescriptor}`,
    addService: `/${constants.content}/${constants.addService}`,
  },
  candidate: {
    profile: `/${constants.candidate}/${constants.profile}`,
    appointments: `/${constants.candidate}/${constants.appointments}`,
    jobPositions: `/${constants.candidate}/${constants.jobPositions}`,
  },
  report: {
    descriptors: `/${constants.report}/${constants.descriptors}`,
    candidate: `/${constants.report}/${constants.candidate}`,
  },
  common: {
    changePassword: `/${constants.common}/${constants.changePassword}`,
    changeProfilePicture: `/${constants.common}/${constants.changeProfilePicture}`,
  },
  admin: `/${constants.admin}`,
  error: `/${constants.error}`,
};
